### ISSUE TITLE
Add possibility to run only subset of tasks

### ISSUE THREAD

**Issue by ricco24** [ricco24/prallel#11]
**Tasks definition:**
```php
$paralel->addTask('cms:domains', ...);
$paralel->addTask('cms:pages', ...);

$paralel->addTask('images:sources', ...);
$paralel->addTask('images:keywords', ...);
```

**Command to run only cms tasks**
```php
parallel:run --subset=cms:*
```

All dependencies outside of subset should be ignored.

**Comment by lulco** [comment]
👍

**Comment by ricco24** [comment]
Implemented in https://github.com/ricco24/parallel/pull/28

**Comment by lulco** [comment]
Subnet or subset? :-P I like subset more then subnet

**Comment by ricco24** [comment]
Now implemented as subnet :-)
