### ISSUE TITLE
Check dependencies names if exists

### ISSUE THREAD

**Issue by lulco** [ricco24/prallel#27]
I just make a typo in dependecy name which cause infinite cycle - no tasks can be run because condition wasn't fullfilled

example:

->addTask(TaskXXX, 'xxx')
->addTask(TaskYYY, 'yyy', ['xxxx'])   // this task will be never executed because task xxxx doesn't exist

**Comment by ricco24** [comment]
Implemented in https://github.com/ricco24/parallel/pull/28
